settings:
  name: "Pruebas Agus"
  description: This is a test with slack integration
  logOnPass: email, telegram 
  #timeout: 60 # the default value is 3600 seconds
  # report: False
  mitigation: Remove secrets from your code if the playbook fails
  #cron: "*/5 * * * ? *"
  count: 20
  
input:
- - value: "Hello World"
    mutate: radamsa
    mutate_qty: 5

  - value: "Hello World"
    mutate: zzuf
    mutate_qty: 5

echo:
  assertStdoutNotEqual: "Hello World"
  input:
  - echo -n ${{input}}