settings:
  name: "Pruebas Agus"
  image: python

install:
  curl:
  - apt update
  - apt install -qy curl screen
  requirements:
  - pip install -r requirements.txt
 
run:
  - screen -dm python3 app.py
  - sleep 1

test:
  assertStdoutContains: 
  - 200 OK
  root:
    - curl -si http://127.0.0.1:5000/
  health:
    assertStdoutContains:
      - ok
    run:
      - curl -si http://127.0.0.1:5000/health